# Exclude vendored and generated code from Rubocop
AllCops:
  Exclude:
    - vendor/**/*
    - bin/*
    - lib/active_model/jobs/version.rb

# Don't require documentation for mocks
Style/Documentation:
  Exclude:
    - spec/support/mocks.rb

# Allow any kind of string literal
Style/StringLiterals:
  Enabled: false
