language: ruby
rvm:
- 2.2
- 2.3
- 2.4
- 2.5
- 2.6
cache: bundler
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: rubygems
  api_key:
    secure: JQWmjd5/4zPBjt33e+ZF5+lmz7nsek6X6Q5Er06q/Qbaeak/uxCd/7hW8mP6mesh6p/OOBIYlRBOxN/GHf7/TWd+n5LrmCye18iyqGQlgwrB3ULoDqSh/GBBLp4u4zI6oBZJA3GoC5mDyDg5Mdf5ye0yVBhbfT3D9+VUyq53xrKI3B3pKztTgvZ/KzF4Gsb3UrN5R0E9Q4NZLrkIlApM517BXKnDTpk1DYZGe12FYZtgZMCkSPtiohZ5qizHDq6HK8ZgPPZ970QEu1jIFUs4luF0qKOCYhO9Yq9UWL1m+eRwa/s/j8Vyww9dPg2x9yReDWcIf0gZMKPBMgVQrnfT/YER5L0cee2XbxI6LdPwkvrx7EQwb5e2z/bzVr7IuiZrewWUTNaO7v9NnKSnS3smfbtu9gK5AYzf0X1z42vWCnCwJNYGAJd2sD1dw80zBtWf0YlonrRnXTUTdapSV3FAZBLFNHL9YNldZ9bjT3cPLhZv/ajk9eL7wOWGVRzghfUTYkTdIGQtH1nasVj99b9cuENj8HEJbnh7r8CgkpyuyZ5YjyZt+VCwCxeImPYv7uJbUlChFipdhC5NTvfIkcsDuXWWP+Va67MTchCnf+chCFD4oRLKuc9atkpSdawpvQ4T5tYiqa5nhscLm79bE2Md/VYqdgWo+JzbPOHq4MqAg4Q=
  gem: active_model-jobs
  on:
    tags: true
    repo: tubbo/active_model-jobs
env:
  global:
    secure: CP6t3YPR9xPYjbvKLpr+I0esOLdurqDeGCffWV0hga1CH+y3U6+S/+ui+F3APQKO9ct8XSZ6pYvZJVUow6o/VJ++e4hFadR3TbToWvjBv6EOUjnREQ6w78eS4JmhpXgSvrZB5SLFNZLUpXoJcxhVRTcA1qBR5oOc5PocuSMvOHGWK0znOqupp1K/46UEouBdwRmty8eKC2UgIxE/jyuBhnkyiUNiLUD13lbnQLnM25MikYd5sPmZPFDWRqwqvWD8j3ZPJjA/WH/+1fkhZbA7HPFCkBWn8lnSO/z8GzGwq/OeEFQvACdiCVBezC5ut0ais9ztIvZloAJL1Dk8AF5eSZLM0gXhhjV9ikWHq5EzM/FVK+haQhF09zRInEYjTEt3XERVmH6geE4qCPm/8sWH9K+sD6norPRoIwdI0cGIfmbzSQmWZXH3afJh3qn1iOuOqKh6F/LrEbmJSArs1FFfxbKjxppAqgi4drmdkgDbNTpEwfMlv9Q7V7ECrCgdXJyG9rVUEGGonWkuHSsDuwiJgEzSdp+KpWvasM5OP1/qBsUV8qqO9uRbh9OtOiMWlxk1j1c2j6oQfTQpPr27iQtD3QwDyhndFv0oY8ksgtDbfJwTCzJzeYtCH+A6Jtrb90PcJpGu6dDFl0B09jnR/8rT38Osnmti7Ghv1lpgJz3Fgvc=
